[AWS|Core] aws needs fog/core/parser to be loaded
without this attempts to require fog/aws on its own result in

NameError: uninitialized constant Fog::Parsers::Base